# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: champi_test_skillet
# label used for menu selection
label: Champi Test Skillet
description: This skillet is only dedicated to test purpose

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - Champi skillets

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
  - name: dns_server_1
    description: Firewall first dns server
    default: 9.9.9.9
    type_hint: ip_address
  - name: dns_server_2
    description: Firewall second dns server
    default: 9.9.9.9
    type_hint: ip_address
  - name: ntp_server_1
    description: Firewall first ntp server
    default: ntp0.oleane.net
    type_hint: fqdn_or_ip
  - name: ntp_server_2
    description: Firewall second ntp server
    default: 194.2.0.58
    type_hint: fqdn_or_ip
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:

  - name: timezone-521884
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <timezone>Europe/Paris</timezone>

  - name: hostname-490452
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <hostname>{{hostname}}</hostname>

  - name: dns-setting-874624
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <dns-setting>
                    <servers>
                      <primary>{{dns_server_1}}</primary>
                      <secondary>{{dns_server_2}}</secondary>
                    </servers>
                  </dns-setting>

  - name: ntp-servers-753448
    xpath: /config/devices/entry[@name="localhost.localdomain"]/deviceconfig/system
    element: |-
        <ntp-servers>
                    <primary-ntp-server>
                      <ntp-server-address>{{ntp_server_1}}</ntp-server-address>
                      <authentication-type>
                        <none/>
                      </authentication-type>
                    </primary-ntp-server>
                    <secondary-ntp-server>
                      <ntp-server-address>{{ntp_server_2}}</ntp-server-address>
                      <authentication-type>
                        <none/>
                      </authentication-type>
                    </secondary-ntp-server>
                  </ntp-servers>

# ---------------------------------------------------------------------
# end of snippets section
